kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{namespace-placeholder}}-master
  namespace: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: master
spec:
  tls:
    - hosts:
        - {{tenant-placeholder}}.yourdomain.com
  rules:
    - host: {{tenant-placeholder}}.yourdomain.com
