kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30252
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30230
  selector:
    app: nginx-ingress
  externalTrafficPolicy: Cluster